" Use minpac for package management
packadd minpac
call minpac#init()

" minpac packages, including itself
call minpac#add('k-takata/minpac', {'type': 'opt'})

" minpac commands
command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()


syntax on
set number
set tabstop=2
set expandtab




" Set the title of the Terminal to the currently open file
function! SetTerminalTitle()
    let titleString = expand('%:t')
    if len(titleString) > 0
        let &titlestring = expand('%:t')
        " this is the format iTerm2 expects when setting the window title
        let args = "\033];".&titlestring."\007"
        let cmd = 'silent !echo -e "'.args.'"'
        execute cmd
        redraw!
    endif
endfunction

autocmd BufEnter * call SetTerminalTitle()

