" Paul Heely
set nocompatible

filetype off

" Use minpac for package management
packadd minpac
call minpac#init()

" minpac packages, including itself so it can be updated
call minpac#add('k-takata/minpac', {'type': 'opt'})

" use fzf for search, reauires external tools fzf and ripgrep
call minpac#add('junegunn/fzf')

" make sense of our todo.txt todos
call minpac#add('freitass/todo.txt-vim')

" make a nice modeline and git config
call minpac#add('vim-airline/vim-airline')
call minpac#add('tpope/vim-fugitive')
call minpac#add('mhinz/vim-signify')

" reformatting is a good thing
call minpac#add('prettier/vim-prettier')

" color schemes
call minpac#add('morhetz/gruvbox')

" get some automated bullet (re)numbering in various modes
call minpac#add('dkarter/bullets.vim')


" minpac commands
command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()
command! PackStatus call minpac#status()


" launch fzf fuzzy serach
nnoremap <C-p> :<C-u>FZF<CR>
nnoremap <leader>ev :vsp ~/.vim/vimrc<CR>





set number
set tabstop=2
set expandtab
set termguicolors


syntax enable
set background=dark
colorscheme gruvbox
filetype plugin indent on



" Compile the markdown file to a word doc
" tried putting this in after/ftplugin/markdown.vim, but neovim won't load it
" reliably
autocmd FileType markdown nnoremap <buffer><silent><localleader>b :!pandoc % -o ~/Documents/Docs/_Inbox/%:r.docx<CR>


